# Generated by Django 4.2 on 2025-07-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vote', models.IntegerField(default=0)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upvote', to='core.answer')),
            ],
        ),
    ]
